/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "libcds2.so"

#include "runtime.h"
#include "cgocall.h"

#ifdef _64BIT
#define SWIG_PARM_SIZE 8
#else
#define SWIG_PARM_SIZE 4
#endif

#pragma dynimport _wrap_kWordSize_get _wrap_kWordSize_get ""
extern void (*_wrap_kWordSize_get)(void*);
static void (*x_wrap_kWordSize_get)(void*) = _wrap_kWordSize_get;

void
·GetKWordSize(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kWordSize_get, &p);
}



#pragma dynimport _wrap_kDoubleWordSize_get _wrap_kDoubleWordSize_get ""
extern void (*_wrap_kDoubleWordSize_get)(void*);
static void (*x_wrap_kDoubleWordSize_get)(void*) = _wrap_kDoubleWordSize_get;

void
·GetKDoubleWordSize(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kDoubleWordSize_get, &p);
}



#pragma dynimport _wrap_kBytesPerWord_get _wrap_kBytesPerWord_get ""
extern void (*_wrap_kBytesPerWord_get)(void*);
static void (*x_wrap_kBytesPerWord_get)(void*) = _wrap_kBytesPerWord_get;

void
·GetKBytesPerWord(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kBytesPerWord_get, &p);
}



#pragma dynimport _wrap_kMaxCDSUchar_get _wrap_kMaxCDSUchar_get ""
extern void (*_wrap_kMaxCDSUchar_get)(void*);
static void (*x_wrap_kMaxCDSUchar_get)(void*) = _wrap_kMaxCDSUchar_get;

void
·GetKMaxCDSUchar(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kMaxCDSUchar_get, &p);
}



#pragma dynimport _wrap_kMaxCDSUint_get _wrap_kMaxCDSUint_get ""
extern void (*_wrap_kMaxCDSUint_get)(void*);
static void (*x_wrap_kMaxCDSUint_get)(void*) = _wrap_kMaxCDSUint_get;

void
·GetKMaxCDSUint(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kMaxCDSUint_get, &p);
}



#pragma dynimport _wrap_kMaxCDSUshort_get _wrap_kMaxCDSUshort_get ""
extern void (*_wrap_kMaxCDSUshort_get)(void*);
static void (*x_wrap_kMaxCDSUshort_get)(void*) = _wrap_kMaxCDSUshort_get;

void
·GetKMaxCDSUshort(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kMaxCDSUshort_get, &p);
}



#pragma dynimport _wrap_kMaxCDSUlong_get _wrap_kMaxCDSUlong_get ""
extern void (*_wrap_kMaxCDSUlong_get)(void*);
static void (*x_wrap_kMaxCDSUlong_get)(void*) = _wrap_kMaxCDSUlong_get;

void
·GetKMaxCDSUlong(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kMaxCDSUlong_get, &p);
}



#pragma dynimport _wrap_kMaxCDSWord_get _wrap_kMaxCDSWord_get ""
extern void (*_wrap_kMaxCDSWord_get)(void*);
static void (*x_wrap_kMaxCDSWord_get)(void*) = _wrap_kMaxCDSWord_get;

void
·GetKMaxCDSWord(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kMaxCDSWord_get, &p);
}



#pragma dynimport _wrap_BitGet _wrap_BitGet ""
extern void (*_wrap_BitGet)(void*);
static void (*x_wrap_BitGet)(void*) = _wrap_BitGet;

void
·BitGet(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitGet, &p);
}



#pragma dynimport _wrap_BitOne _wrap_BitOne ""
extern void (*_wrap_BitOne)(void*);
static void (*x_wrap_BitOne)(void*) = _wrap_BitOne;

void
·_swig_wrap_BitOne(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitOne, &p);
}



#pragma dynimport _wrap_BitZero _wrap_BitZero ""
extern void (*_wrap_BitZero)(void*);
static void (*x_wrap_BitZero)(void*) = _wrap_BitZero;

void
·_swig_wrap_BitZero(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitZero, &p);
}



#pragma dynimport _wrap_BitSet__SWIG_0 _wrap_BitSet__SWIG_0 ""
extern void (*_wrap_BitSet__SWIG_0)(void*);
static void (*x_wrap_BitSet__SWIG_0)(void*) = _wrap_BitSet__SWIG_0;

void
·_swig_wrap_BitSet__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSet__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSet__SWIG_1 _wrap_BitSet__SWIG_1 ""
extern void (*_wrap_BitSet__SWIG_1)(void*);
static void (*x_wrap_BitSet__SWIG_1)(void*) = _wrap_BitSet__SWIG_1;

void
·_swig_wrap_BitSet__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSet__SWIG_1, &p);
}



#pragma dynimport _wrap_WordsLength _wrap_WordsLength ""
extern void (*_wrap_WordsLength)(void*);
static void (*x_wrap_WordsLength)(void*) = _wrap_WordsLength;

void
·WordsLength(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_WordsLength, &p);
}



#pragma dynimport _wrap_SafeCeil _wrap_SafeCeil ""
extern void (*_wrap_SafeCeil)(void*);
static void (*x_wrap_SafeCeil)(void*) = _wrap_SafeCeil;

void
·SafeCeil(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SafeCeil, &p);
}



#pragma dynimport _wrap_GetVarField _wrap_GetVarField ""
extern void (*_wrap_GetVarField)(void*);
static void (*x_wrap_GetVarField)(void*) = _wrap_GetVarField;

void
·GetVarField(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_GetVarField, &p);
}



#pragma dynimport _wrap_SetVarField _wrap_SetVarField ""
extern void (*_wrap_SetVarField)(void*);
static void (*x_wrap_SetVarField)(void*) = _wrap_SetVarField;

void
·_swig_wrap_SetVarField(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SetVarField, &p);
}



#pragma dynimport _wrap_GetField _wrap_GetField ""
extern void (*_wrap_GetField)(void*);
static void (*x_wrap_GetField)(void*) = _wrap_GetField;

void
·GetField(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_GetField, &p);
}



#pragma dynimport _wrap_SetField _wrap_SetField ""
extern void (*_wrap_SetField)(void*);
static void (*x_wrap_SetField)(void*) = _wrap_SetField;

void
·_swig_wrap_SetField(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_SetField, &p);
}



#pragma dynimport _wrap_GetField8 _wrap_GetField8 ""
extern void (*_wrap_GetField8)(void*);
static void (*x_wrap_GetField8)(void*) = _wrap_GetField8;

void
·GetField8(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_GetField8, &p);
}



#pragma dynimport _wrap_GetField16 _wrap_GetField16 ""
extern void (*_wrap_GetField16)(void*);
static void (*x_wrap_GetField16)(void*) = _wrap_GetField16;

void
·GetField16(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_GetField16, &p);
}



#pragma dynimport _wrap_GetField32 _wrap_GetField32 ""
extern void (*_wrap_GetField32)(void*);
static void (*x_wrap_GetField32)(void*) = _wrap_GetField32;

void
·GetField32(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_GetField32, &p);
}



#pragma dynimport _wrap_GetField2 _wrap_GetField2 ""
extern void (*_wrap_GetField2)(void*);
static void (*x_wrap_GetField2)(void*) = _wrap_GetField2;

void
·GetField2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_GetField2, &p);
}



#pragma dynimport _wrap_GetField4 _wrap_GetField4 ""
extern void (*_wrap_GetField4)(void*);
static void (*x_wrap_GetField4)(void*) = _wrap_GetField4;

void
·GetField4(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_GetField4, &p);
}



#pragma dynimport _wrap_msb _wrap_msb ""
extern void (*_wrap_msb)(void*);
static void (*x_wrap_msb)(void*) = _wrap_msb;

void
·Msb(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_msb, &p);
}



#pragma dynimport _wrap_popcount _wrap_popcount ""
extern void (*_wrap_popcount)(void*);
static void (*x_wrap_popcount)(void*) = _wrap_popcount;

void
·Popcount(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_popcount, &p);
}



#pragma dynimport _wrap_lsb _wrap_lsb ""
extern void (*_wrap_lsb)(void*);
static void (*x_wrap_lsb)(void*) = _wrap_lsb;

void
·Lsb(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_lsb, &p);
}



#pragma dynimport _wrap_Xselect _wrap_Xselect ""
extern void (*_wrap_Xselect)(void*);
static void (*x_wrap_Xselect)(void*) = _wrap_Xselect;

void
·Xselect(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Xselect, &p);
}



#pragma dynimport _wrap_PrintBinary _wrap_PrintBinary ""
extern void (*_wrap_PrintBinary)(void*);
static void (*x_wrap_PrintBinary)(void*) = _wrap_PrintBinary;

void
·_swig_wrap_PrintBinary(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PrintBinary, &p);
}



#pragma dynimport _wrap_new_ReferenceCounted _wrap_new_ReferenceCounted ""
extern void (*_wrap_new_ReferenceCounted)(void*);
static void (*x_wrap_new_ReferenceCounted)(void*) = _wrap_new_ReferenceCounted;

void
·_swig_wrap_new_ReferenceCounted(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_ReferenceCounted, &p);
}



#pragma dynimport _wrap_delete_ReferenceCounted _wrap_delete_ReferenceCounted ""
extern void (*_wrap_delete_ReferenceCounted)(void*);
static void (*x_wrap_delete_ReferenceCounted)(void*) = _wrap_delete_ReferenceCounted;

void
·_swig_wrap_delete_ReferenceCounted(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_ReferenceCounted, &p);
}



#pragma dynimport _wrap_ReferenceCounted_Unuse _wrap_ReferenceCounted_Unuse ""
extern void (*_wrap_ReferenceCounted_Unuse)(void*);
static void (*x_wrap_ReferenceCounted_Unuse)(void*) = _wrap_ReferenceCounted_Unuse;

void
·_swig_wrap_ReferenceCounted_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ReferenceCounted_Unuse, &p);
}



#pragma dynimport _wrap_ReferenceCounted_Use _wrap_ReferenceCounted_Use ""
extern void (*_wrap_ReferenceCounted_Use)(void*);
static void (*x_wrap_ReferenceCounted_Use)(void*) = _wrap_ReferenceCounted_Use;

void
·_swig_wrap_ReferenceCounted_Use(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_ReferenceCounted_Use, &p);
}



#pragma dynimport _wrap_kBitSequenceOneLevelRankID_get _wrap_kBitSequenceOneLevelRankID_get ""
extern void (*_wrap_kBitSequenceOneLevelRankID_get)(void*);
static void (*x_wrap_kBitSequenceOneLevelRankID_get)(void*) = _wrap_kBitSequenceOneLevelRankID_get;

void
·GetKBitSequenceOneLevelRankID(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_kBitSequenceOneLevelRankID_get, &p);
}



#pragma dynimport _wrap_delete_BitSequence _wrap_delete_BitSequence ""
extern void (*_wrap_delete_BitSequence)(void*);
static void (*x_wrap_delete_BitSequence)(void*) = _wrap_delete_BitSequence;

void
·_swig_wrap_delete_BitSequence(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_BitSequence, &p);
}



#pragma dynimport _wrap_BitSequence_Rank0__SWIG_0 _wrap_BitSequence_Rank0__SWIG_0 ""
extern void (*_wrap_BitSequence_Rank0__SWIG_0)(void*);
static void (*x_wrap_BitSequence_Rank0__SWIG_0)(void*) = _wrap_BitSequence_Rank0__SWIG_0;

void
·_swig_wrap_BitSequence_Rank0__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Rank0__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSequence_Rank0__SWIG_1 _wrap_BitSequence_Rank0__SWIG_1 ""
extern void (*_wrap_BitSequence_Rank0__SWIG_1)(void*);
static void (*x_wrap_BitSequence_Rank0__SWIG_1)(void*) = _wrap_BitSequence_Rank0__SWIG_1;

void
·_swig_wrap_BitSequence_Rank0__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Rank0__SWIG_1, &p);
}



#pragma dynimport _wrap_BitSequence_Select0__SWIG_0 _wrap_BitSequence_Select0__SWIG_0 ""
extern void (*_wrap_BitSequence_Select0__SWIG_0)(void*);
static void (*x_wrap_BitSequence_Select0__SWIG_0)(void*) = _wrap_BitSequence_Select0__SWIG_0;

void
·_swig_wrap_BitSequence_Select0__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Select0__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSequence_Select0__SWIG_1 _wrap_BitSequence_Select0__SWIG_1 ""
extern void (*_wrap_BitSequence_Select0__SWIG_1)(void*);
static void (*x_wrap_BitSequence_Select0__SWIG_1)(void*) = _wrap_BitSequence_Select0__SWIG_1;

void
·_swig_wrap_BitSequence_Select0__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Select0__SWIG_1, &p);
}



#pragma dynimport _wrap_BitSequence_Rank1__SWIG_0 _wrap_BitSequence_Rank1__SWIG_0 ""
extern void (*_wrap_BitSequence_Rank1__SWIG_0)(void*);
static void (*x_wrap_BitSequence_Rank1__SWIG_0)(void*) = _wrap_BitSequence_Rank1__SWIG_0;

void
·_swig_wrap_BitSequence_Rank1__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Rank1__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSequence_Rank1__SWIG_1 _wrap_BitSequence_Rank1__SWIG_1 ""
extern void (*_wrap_BitSequence_Rank1__SWIG_1)(void*);
static void (*x_wrap_BitSequence_Rank1__SWIG_1)(void*) = _wrap_BitSequence_Rank1__SWIG_1;

void
·_swig_wrap_BitSequence_Rank1__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Rank1__SWIG_1, &p);
}



#pragma dynimport _wrap_BitSequence_Select1__SWIG_0 _wrap_BitSequence_Select1__SWIG_0 ""
extern void (*_wrap_BitSequence_Select1__SWIG_0)(void*);
static void (*x_wrap_BitSequence_Select1__SWIG_0)(void*) = _wrap_BitSequence_Select1__SWIG_0;

void
·_swig_wrap_BitSequence_Select1__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Select1__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSequence_Select1__SWIG_1 _wrap_BitSequence_Select1__SWIG_1 ""
extern void (*_wrap_BitSequence_Select1__SWIG_1)(void*);
static void (*x_wrap_BitSequence_Select1__SWIG_1)(void*) = _wrap_BitSequence_Select1__SWIG_1;

void
·_swig_wrap_BitSequence_Select1__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Select1__SWIG_1, &p);
}



#pragma dynimport _wrap_BitSequence_SelectNext1 _wrap_BitSequence_SelectNext1 ""
extern void (*_wrap_BitSequence_SelectNext1)(void*);
static void (*x_wrap_BitSequence_SelectNext1)(void*) = _wrap_BitSequence_SelectNext1;

void
·_swig_wrap_BitSequence_SelectNext1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_SelectNext1, &p);
}



#pragma dynimport _wrap_BitSequence_SelectNext0 _wrap_BitSequence_SelectNext0 ""
extern void (*_wrap_BitSequence_SelectNext0)(void*);
static void (*x_wrap_BitSequence_SelectNext0)(void*) = _wrap_BitSequence_SelectNext0;

void
·_swig_wrap_BitSequence_SelectNext0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_SelectNext0, &p);
}



#pragma dynimport _wrap_BitSequence_SelectPrev1 _wrap_BitSequence_SelectPrev1 ""
extern void (*_wrap_BitSequence_SelectPrev1)(void*);
static void (*x_wrap_BitSequence_SelectPrev1)(void*) = _wrap_BitSequence_SelectPrev1;

void
·_swig_wrap_BitSequence_SelectPrev1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_SelectPrev1, &p);
}



#pragma dynimport _wrap_BitSequence_SelectPrev0 _wrap_BitSequence_SelectPrev0 ""
extern void (*_wrap_BitSequence_SelectPrev0)(void*);
static void (*x_wrap_BitSequence_SelectPrev0)(void*) = _wrap_BitSequence_SelectPrev0;

void
·_swig_wrap_BitSequence_SelectPrev0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_SelectPrev0, &p);
}



#pragma dynimport _wrap_BitSequence_Access__SWIG_0 _wrap_BitSequence_Access__SWIG_0 ""
extern void (*_wrap_BitSequence_Access__SWIG_0)(void*);
static void (*x_wrap_BitSequence_Access__SWIG_0)(void*) = _wrap_BitSequence_Access__SWIG_0;

void
·_swig_wrap_BitSequence_Access__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Access__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSequence_Access__SWIG_1 _wrap_BitSequence_Access__SWIG_1 ""
extern void (*_wrap_BitSequence_Access__SWIG_1)(void*);
static void (*x_wrap_BitSequence_Access__SWIG_1)(void*) = _wrap_BitSequence_Access__SWIG_1;

void
·_swig_wrap_BitSequence_Access__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Access__SWIG_1, &p);
}



#pragma dynimport _wrap_BitSequence_GetLength _wrap_BitSequence_GetLength ""
extern void (*_wrap_BitSequence_GetLength)(void*);
static void (*x_wrap_BitSequence_GetLength)(void*) = _wrap_BitSequence_GetLength;

void
·_swig_wrap_BitSequence_GetLength(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_GetLength, &p);
}



#pragma dynimport _wrap_BitSequence_CountOnes _wrap_BitSequence_CountOnes ""
extern void (*_wrap_BitSequence_CountOnes)(void*);
static void (*x_wrap_BitSequence_CountOnes)(void*) = _wrap_BitSequence_CountOnes;

void
·_swig_wrap_BitSequence_CountOnes(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_CountOnes, &p);
}



#pragma dynimport _wrap_BitSequence_CountZeros _wrap_BitSequence_CountZeros ""
extern void (*_wrap_BitSequence_CountZeros)(void*);
static void (*x_wrap_BitSequence_CountZeros)(void*) = _wrap_BitSequence_CountZeros;

void
·_swig_wrap_BitSequence_CountZeros(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_CountZeros, &p);
}



#pragma dynimport _wrap_BitSequence_GetSize _wrap_BitSequence_GetSize ""
extern void (*_wrap_BitSequence_GetSize)(void*);
static void (*x_wrap_BitSequence_GetSize)(void*) = _wrap_BitSequence_GetSize;

void
·_swig_wrap_BitSequence_GetSize(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_GetSize, &p);
}



#pragma dynimport _wrap_BitSequence_Save _wrap_BitSequence_Save ""
extern void (*_wrap_BitSequence_Save)(void*);
static void (*x_wrap_BitSequence_Save)(void*) = _wrap_BitSequence_Save;

void
·_swig_wrap_BitSequence_Save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Save, &p);
}



#pragma dynimport _wrap_BitSequence_Load _wrap_BitSequence_Load ""
extern void (*_wrap_BitSequence_Load)(void*);
static void (*x_wrap_BitSequence_Load)(void*) = _wrap_BitSequence_Load;

void
·_swig_wrap_BitSequence_Load(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Load, &p);
}



#pragma dynimport _wrap_BitSequence_Unuse _wrap_BitSequence_Unuse ""
extern void (*_wrap_BitSequence_Unuse)(void*);
static void (*x_wrap_BitSequence_Unuse)(void*) = _wrap_BitSequence_Unuse;

void
·_swig_wrap_BitSequence_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Unuse, &p);
}



#pragma dynimport _wrap_BitSequence_Use _wrap_BitSequence_Use ""
extern void (*_wrap_BitSequence_Use)(void*);
static void (*x_wrap_BitSequence_Use)(void*) = _wrap_BitSequence_Use;

void
·_swig_wrap_BitSequence_Use(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequence_Use, &p);
}



#pragma dynimport _wrap_new_BitSequenceOneLevelRank _wrap_new_BitSequenceOneLevelRank ""
extern void (*_wrap_new_BitSequenceOneLevelRank)(void*);
static void (*x_wrap_new_BitSequenceOneLevelRank)(void*) = _wrap_new_BitSequenceOneLevelRank;

void
·_swig_wrap_new_BitSequenceOneLevelRank(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_BitSequenceOneLevelRank, &p);
}



#pragma dynimport _wrap_delete_BitSequenceOneLevelRank _wrap_delete_BitSequenceOneLevelRank ""
extern void (*_wrap_delete_BitSequenceOneLevelRank)(void*);
static void (*x_wrap_delete_BitSequenceOneLevelRank)(void*) = _wrap_delete_BitSequenceOneLevelRank;

void
·_swig_wrap_delete_BitSequenceOneLevelRank(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_BitSequenceOneLevelRank, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Rank0 _wrap_BitSequenceOneLevelRank_Rank0 ""
extern void (*_wrap_BitSequenceOneLevelRank_Rank0)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Rank0)(void*) = _wrap_BitSequenceOneLevelRank_Rank0;

void
·_swig_wrap_BitSequenceOneLevelRank_Rank0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Rank0, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Select0 _wrap_BitSequenceOneLevelRank_Select0 ""
extern void (*_wrap_BitSequenceOneLevelRank_Select0)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Select0)(void*) = _wrap_BitSequenceOneLevelRank_Select0;

void
·_swig_wrap_BitSequenceOneLevelRank_Select0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Select0, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Rank1__SWIG_0 _wrap_BitSequenceOneLevelRank_Rank1__SWIG_0 ""
extern void (*_wrap_BitSequenceOneLevelRank_Rank1__SWIG_0)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Rank1__SWIG_0)(void*) = _wrap_BitSequenceOneLevelRank_Rank1__SWIG_0;

void
·_swig_wrap_BitSequenceOneLevelRank_Rank1__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Rank1__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Rank1__SWIG_1 _wrap_BitSequenceOneLevelRank_Rank1__SWIG_1 ""
extern void (*_wrap_BitSequenceOneLevelRank_Rank1__SWIG_1)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Rank1__SWIG_1)(void*) = _wrap_BitSequenceOneLevelRank_Rank1__SWIG_1;

void
·_swig_wrap_BitSequenceOneLevelRank_Rank1__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Rank1__SWIG_1, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Select1 _wrap_BitSequenceOneLevelRank_Select1 ""
extern void (*_wrap_BitSequenceOneLevelRank_Select1)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Select1)(void*) = _wrap_BitSequenceOneLevelRank_Select1;

void
·_swig_wrap_BitSequenceOneLevelRank_Select1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Select1, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_SelectNext1 _wrap_BitSequenceOneLevelRank_SelectNext1 ""
extern void (*_wrap_BitSequenceOneLevelRank_SelectNext1)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_SelectNext1)(void*) = _wrap_BitSequenceOneLevelRank_SelectNext1;

void
·_swig_wrap_BitSequenceOneLevelRank_SelectNext1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_SelectNext1, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Access__SWIG_0 _wrap_BitSequenceOneLevelRank_Access__SWIG_0 ""
extern void (*_wrap_BitSequenceOneLevelRank_Access__SWIG_0)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Access__SWIG_0)(void*) = _wrap_BitSequenceOneLevelRank_Access__SWIG_0;

void
·_swig_wrap_BitSequenceOneLevelRank_Access__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Access__SWIG_0, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Access__SWIG_1 _wrap_BitSequenceOneLevelRank_Access__SWIG_1 ""
extern void (*_wrap_BitSequenceOneLevelRank_Access__SWIG_1)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Access__SWIG_1)(void*) = _wrap_BitSequenceOneLevelRank_Access__SWIG_1;

void
·_swig_wrap_BitSequenceOneLevelRank_Access__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Access__SWIG_1, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_GetLength _wrap_BitSequenceOneLevelRank_GetLength ""
extern void (*_wrap_BitSequenceOneLevelRank_GetLength)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_GetLength)(void*) = _wrap_BitSequenceOneLevelRank_GetLength;

void
·_swig_wrap_BitSequenceOneLevelRank_GetLength(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_GetLength, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_GetSize _wrap_BitSequenceOneLevelRank_GetSize ""
extern void (*_wrap_BitSequenceOneLevelRank_GetSize)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_GetSize)(void*) = _wrap_BitSequenceOneLevelRank_GetSize;

void
·_swig_wrap_BitSequenceOneLevelRank_GetSize(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_GetSize, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Save _wrap_BitSequenceOneLevelRank_Save ""
extern void (*_wrap_BitSequenceOneLevelRank_Save)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Save)(void*) = _wrap_BitSequenceOneLevelRank_Save;

void
·_swig_wrap_BitSequenceOneLevelRank_Save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Save, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Load _wrap_BitSequenceOneLevelRank_Load ""
extern void (*_wrap_BitSequenceOneLevelRank_Load)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Load)(void*) = _wrap_BitSequenceOneLevelRank_Load;

void
·_swig_wrap_BitSequenceOneLevelRank_Load(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Load, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_SelectNext0 _wrap_BitSequenceOneLevelRank_SelectNext0 ""
extern void (*_wrap_BitSequenceOneLevelRank_SelectNext0)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_SelectNext0)(void*) = _wrap_BitSequenceOneLevelRank_SelectNext0;

void
·_swig_wrap_BitSequenceOneLevelRank_SelectNext0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_SelectNext0, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_SelectPrev1 _wrap_BitSequenceOneLevelRank_SelectPrev1 ""
extern void (*_wrap_BitSequenceOneLevelRank_SelectPrev1)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_SelectPrev1)(void*) = _wrap_BitSequenceOneLevelRank_SelectPrev1;

void
·_swig_wrap_BitSequenceOneLevelRank_SelectPrev1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_SelectPrev1, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_SelectPrev0 _wrap_BitSequenceOneLevelRank_SelectPrev0 ""
extern void (*_wrap_BitSequenceOneLevelRank_SelectPrev0)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_SelectPrev0)(void*) = _wrap_BitSequenceOneLevelRank_SelectPrev0;

void
·_swig_wrap_BitSequenceOneLevelRank_SelectPrev0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_SelectPrev0, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_CountOnes _wrap_BitSequenceOneLevelRank_CountOnes ""
extern void (*_wrap_BitSequenceOneLevelRank_CountOnes)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_CountOnes)(void*) = _wrap_BitSequenceOneLevelRank_CountOnes;

void
·_swig_wrap_BitSequenceOneLevelRank_CountOnes(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_CountOnes, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_CountZeros _wrap_BitSequenceOneLevelRank_CountZeros ""
extern void (*_wrap_BitSequenceOneLevelRank_CountZeros)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_CountZeros)(void*) = _wrap_BitSequenceOneLevelRank_CountZeros;

void
·_swig_wrap_BitSequenceOneLevelRank_CountZeros(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_CountZeros, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Unuse _wrap_BitSequenceOneLevelRank_Unuse ""
extern void (*_wrap_BitSequenceOneLevelRank_Unuse)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Unuse)(void*) = _wrap_BitSequenceOneLevelRank_Unuse;

void
·_swig_wrap_BitSequenceOneLevelRank_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Unuse, &p);
}



#pragma dynimport _wrap_BitSequenceOneLevelRank_Use _wrap_BitSequenceOneLevelRank_Use ""
extern void (*_wrap_BitSequenceOneLevelRank_Use)(void*);
static void (*x_wrap_BitSequenceOneLevelRank_Use)(void*) = _wrap_BitSequenceOneLevelRank_Use;

void
·_swig_wrap_BitSequenceOneLevelRank_Use(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_BitSequenceOneLevelRank_Use, &p);
}



#pragma dynimport _wrap_delete_Array _wrap_delete_Array ""
extern void (*_wrap_delete_Array)(void*);
static void (*x_wrap_delete_Array)(void*) = _wrap_delete_Array;

void
·_swig_wrap_delete_Array(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Array, &p);
}



#pragma dynimport _wrap_Array_GetField _wrap_Array_GetField ""
extern void (*_wrap_Array_GetField)(void*);
static void (*x_wrap_Array_GetField)(void*) = _wrap_Array_GetField;

void
·_swig_wrap_Array_GetField(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_GetField, &p);
}



#pragma dynimport _wrap_Array_SetField _wrap_Array_SetField ""
extern void (*_wrap_Array_SetField)(void*);
static void (*x_wrap_Array_SetField)(void*) = _wrap_Array_SetField;

void
·_swig_wrap_Array_SetField(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_SetField, &p);
}



#pragma dynimport _wrap_Array_Save _wrap_Array_Save ""
extern void (*_wrap_Array_Save)(void*);
static void (*x_wrap_Array_Save)(void*) = _wrap_Array_Save;

void
·_swig_wrap_Array_Save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_Save, &p);
}



#pragma dynimport _wrap_Array_GetSize _wrap_Array_GetSize ""
extern void (*_wrap_Array_GetSize)(void*);
static void (*x_wrap_Array_GetSize)(void*) = _wrap_Array_GetSize;

void
·_swig_wrap_Array_GetSize(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_GetSize, &p);
}



#pragma dynimport _wrap_Array_GetLength _wrap_Array_GetLength ""
extern void (*_wrap_Array_GetLength)(void*);
static void (*x_wrap_Array_GetLength)(void*) = _wrap_Array_GetLength;

void
·_swig_wrap_Array_GetLength(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_GetLength, &p);
}



#pragma dynimport _wrap_Array_GetMax _wrap_Array_GetMax ""
extern void (*_wrap_Array_GetMax)(void*);
static void (*x_wrap_Array_GetMax)(void*) = _wrap_Array_GetMax;

void
·_swig_wrap_Array_GetMax(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_GetMax, &p);
}



#pragma dynimport _wrap_Array_LowerBound__SWIG_0 _wrap_Array_LowerBound__SWIG_0 ""
extern void (*_wrap_Array_LowerBound__SWIG_0)(void*);
static void (*x_wrap_Array_LowerBound__SWIG_0)(void*) = _wrap_Array_LowerBound__SWIG_0;

void
·_swig_wrap_Array_LowerBound__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_LowerBound__SWIG_0, &p);
}



#pragma dynimport _wrap_Array_LowerBound__SWIG_1 _wrap_Array_LowerBound__SWIG_1 ""
extern void (*_wrap_Array_LowerBound__SWIG_1)(void*);
static void (*x_wrap_Array_LowerBound__SWIG_1)(void*) = _wrap_Array_LowerBound__SWIG_1;

void
·_swig_wrap_Array_LowerBound__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_LowerBound__SWIG_1, &p);
}



#pragma dynimport _wrap_Array_LowerBoundExp__SWIG_0 _wrap_Array_LowerBoundExp__SWIG_0 ""
extern void (*_wrap_Array_LowerBoundExp__SWIG_0)(void*);
static void (*x_wrap_Array_LowerBoundExp__SWIG_0)(void*) = _wrap_Array_LowerBoundExp__SWIG_0;

void
·_swig_wrap_Array_LowerBoundExp__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_LowerBoundExp__SWIG_0, &p);
}



#pragma dynimport _wrap_Array_LowerBoundExp__SWIG_1 _wrap_Array_LowerBoundExp__SWIG_1 ""
extern void (*_wrap_Array_LowerBoundExp__SWIG_1)(void*);
static void (*x_wrap_Array_LowerBoundExp__SWIG_1)(void*) = _wrap_Array_LowerBoundExp__SWIG_1;

void
·_swig_wrap_Array_LowerBoundExp__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_LowerBoundExp__SWIG_1, &p);
}



#pragma dynimport _wrap_Array_UpperBound__SWIG_0 _wrap_Array_UpperBound__SWIG_0 ""
extern void (*_wrap_Array_UpperBound__SWIG_0)(void*);
static void (*x_wrap_Array_UpperBound__SWIG_0)(void*) = _wrap_Array_UpperBound__SWIG_0;

void
·_swig_wrap_Array_UpperBound__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_UpperBound__SWIG_0, &p);
}



#pragma dynimport _wrap_Array_UpperBound__SWIG_1 _wrap_Array_UpperBound__SWIG_1 ""
extern void (*_wrap_Array_UpperBound__SWIG_1)(void*);
static void (*x_wrap_Array_UpperBound__SWIG_1)(void*) = _wrap_Array_UpperBound__SWIG_1;

void
·_swig_wrap_Array_UpperBound__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_UpperBound__SWIG_1, &p);
}



#pragma dynimport _wrap_Array_BinarySearch__SWIG_0 _wrap_Array_BinarySearch__SWIG_0 ""
extern void (*_wrap_Array_BinarySearch__SWIG_0)(void*);
static void (*x_wrap_Array_BinarySearch__SWIG_0)(void*) = _wrap_Array_BinarySearch__SWIG_0;

void
·_swig_wrap_Array_BinarySearch__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_BinarySearch__SWIG_0, &p);
}



#pragma dynimport _wrap_Array_BinarySearch__SWIG_1 _wrap_Array_BinarySearch__SWIG_1 ""
extern void (*_wrap_Array_BinarySearch__SWIG_1)(void*);
static void (*x_wrap_Array_BinarySearch__SWIG_1)(void*) = _wrap_Array_BinarySearch__SWIG_1;

void
·_swig_wrap_Array_BinarySearch__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_BinarySearch__SWIG_1, &p);
}



#pragma dynimport _wrap_Array_Load _wrap_Array_Load ""
extern void (*_wrap_Array_Load)(void*);
static void (*x_wrap_Array_Load)(void*) = _wrap_Array_Load;

void
·_swig_wrap_Array_Load(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_Load, &p);
}



#pragma dynimport _wrap_Array_Create__SWIG_0 _wrap_Array_Create__SWIG_0 ""
extern void (*_wrap_Array_Create__SWIG_0)(void*);
static void (*x_wrap_Array_Create__SWIG_0)(void*) = _wrap_Array_Create__SWIG_0;

void
·_swig_wrap_Array_Create__SWIG_0(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_Create__SWIG_0, &p);
}



#pragma dynimport _wrap_Array_Create__SWIG_1 _wrap_Array_Create__SWIG_1 ""
extern void (*_wrap_Array_Create__SWIG_1)(void*);
static void (*x_wrap_Array_Create__SWIG_1)(void*) = _wrap_Array_Create__SWIG_1;

void
·_swig_wrap_Array_Create__SWIG_1(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_Create__SWIG_1, &p);
}



#pragma dynimport _wrap_Array_Create__SWIG_2 _wrap_Array_Create__SWIG_2 ""
extern void (*_wrap_Array_Create__SWIG_2)(void*);
static void (*x_wrap_Array_Create__SWIG_2)(void*) = _wrap_Array_Create__SWIG_2;

void
·_swig_wrap_Array_Create__SWIG_2(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_Create__SWIG_2, &p);
}



#pragma dynimport _wrap_Array_Unuse _wrap_Array_Unuse ""
extern void (*_wrap_Array_Unuse)(void*);
static void (*x_wrap_Array_Unuse)(void*) = _wrap_Array_Unuse;

void
·_swig_wrap_Array_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_Unuse, &p);
}



#pragma dynimport _wrap_Array_Use _wrap_Array_Use ""
extern void (*_wrap_Array_Use)(void*);
static void (*x_wrap_Array_Use)(void*) = _wrap_Array_Use;

void
·_swig_wrap_Array_Use(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Array_Use, &p);
}



#pragma dynimport _wrap_delete_Mapper _wrap_delete_Mapper ""
extern void (*_wrap_delete_Mapper)(void*);
static void (*x_wrap_delete_Mapper)(void*) = _wrap_delete_Mapper;

void
·_swig_wrap_delete_Mapper(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Mapper, &p);
}



#pragma dynimport _wrap_Mapper_Map _wrap_Mapper_Map ""
extern void (*_wrap_Mapper_Map)(void*);
static void (*x_wrap_Mapper_Map)(void*) = _wrap_Mapper_Map;

void
·_swig_wrap_Mapper_Map(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Mapper_Map, &p);
}



#pragma dynimport _wrap_Mapper_Unmap _wrap_Mapper_Unmap ""
extern void (*_wrap_Mapper_Unmap)(void*);
static void (*x_wrap_Mapper_Unmap)(void*) = _wrap_Mapper_Unmap;

void
·_swig_wrap_Mapper_Unmap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Mapper_Unmap, &p);
}



#pragma dynimport _wrap_Mapper_GetSize _wrap_Mapper_GetSize ""
extern void (*_wrap_Mapper_GetSize)(void*);
static void (*x_wrap_Mapper_GetSize)(void*) = _wrap_Mapper_GetSize;

void
·_swig_wrap_Mapper_GetSize(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Mapper_GetSize, &p);
}



#pragma dynimport _wrap_Mapper_Save _wrap_Mapper_Save ""
extern void (*_wrap_Mapper_Save)(void*);
static void (*x_wrap_Mapper_Save)(void*) = _wrap_Mapper_Save;

void
·_swig_wrap_Mapper_Save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Mapper_Save, &p);
}



#pragma dynimport _wrap_Mapper_Load _wrap_Mapper_Load ""
extern void (*_wrap_Mapper_Load)(void*);
static void (*x_wrap_Mapper_Load)(void*) = _wrap_Mapper_Load;

void
·_swig_wrap_Mapper_Load(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Mapper_Load, &p);
}



#pragma dynimport _wrap_Mapper_Unuse _wrap_Mapper_Unuse ""
extern void (*_wrap_Mapper_Unuse)(void*);
static void (*x_wrap_Mapper_Unuse)(void*) = _wrap_Mapper_Unuse;

void
·_swig_wrap_Mapper_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Mapper_Unuse, &p);
}



#pragma dynimport _wrap_Mapper_Use _wrap_Mapper_Use ""
extern void (*_wrap_Mapper_Use)(void*);
static void (*x_wrap_Mapper_Use)(void*) = _wrap_Mapper_Use;

void
·_swig_wrap_Mapper_Use(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Mapper_Use, &p);
}



#pragma dynimport _wrap_new_MapperNone _wrap_new_MapperNone ""
extern void (*_wrap_new_MapperNone)(void*);
static void (*x_wrap_new_MapperNone)(void*) = _wrap_new_MapperNone;

void
·_swig_wrap_new_MapperNone(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_MapperNone, &p);
}



#pragma dynimport _wrap_delete_MapperNone _wrap_delete_MapperNone ""
extern void (*_wrap_delete_MapperNone)(void*);
static void (*x_wrap_delete_MapperNone)(void*) = _wrap_delete_MapperNone;

void
·_swig_wrap_delete_MapperNone(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_MapperNone, &p);
}



#pragma dynimport _wrap_MapperNone_Map _wrap_MapperNone_Map ""
extern void (*_wrap_MapperNone_Map)(void*);
static void (*x_wrap_MapperNone_Map)(void*) = _wrap_MapperNone_Map;

void
·_swig_wrap_MapperNone_Map(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MapperNone_Map, &p);
}



#pragma dynimport _wrap_MapperNone_Unmap _wrap_MapperNone_Unmap ""
extern void (*_wrap_MapperNone_Unmap)(void*);
static void (*x_wrap_MapperNone_Unmap)(void*) = _wrap_MapperNone_Unmap;

void
·_swig_wrap_MapperNone_Unmap(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MapperNone_Unmap, &p);
}



#pragma dynimport _wrap_MapperNone_GetSize _wrap_MapperNone_GetSize ""
extern void (*_wrap_MapperNone_GetSize)(void*);
static void (*x_wrap_MapperNone_GetSize)(void*) = _wrap_MapperNone_GetSize;

void
·_swig_wrap_MapperNone_GetSize(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MapperNone_GetSize, &p);
}



#pragma dynimport _wrap_MapperNone_Save _wrap_MapperNone_Save ""
extern void (*_wrap_MapperNone_Save)(void*);
static void (*x_wrap_MapperNone_Save)(void*) = _wrap_MapperNone_Save;

void
·_swig_wrap_MapperNone_Save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MapperNone_Save, &p);
}



#pragma dynimport _wrap_MapperNone_Load _wrap_MapperNone_Load ""
extern void (*_wrap_MapperNone_Load)(void*);
static void (*x_wrap_MapperNone_Load)(void*) = _wrap_MapperNone_Load;

void
·_swig_wrap_MapperNone_Load(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MapperNone_Load, &p);
}



#pragma dynimport _wrap_MapperNone_Unuse _wrap_MapperNone_Unuse ""
extern void (*_wrap_MapperNone_Unuse)(void*);
static void (*x_wrap_MapperNone_Unuse)(void*) = _wrap_MapperNone_Unuse;

void
·_swig_wrap_MapperNone_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MapperNone_Unuse, &p);
}



#pragma dynimport _wrap_MapperNone_Use _wrap_MapperNone_Use ""
extern void (*_wrap_MapperNone_Use)(void*);
static void (*x_wrap_MapperNone_Use)(void*) = _wrap_MapperNone_Use;

void
·_swig_wrap_MapperNone_Use(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_MapperNone_Use, &p);
}



#pragma dynimport _wrap_delete_Coder _wrap_delete_Coder ""
extern void (*_wrap_delete_Coder)(void*);
static void (*x_wrap_delete_Coder)(void*) = _wrap_delete_Coder;

void
·_swig_wrap_delete_Coder(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Coder, &p);
}



#pragma dynimport _wrap_Coder_Encode _wrap_Coder_Encode ""
extern void (*_wrap_Coder_Encode)(void*);
static void (*x_wrap_Coder_Encode)(void*) = _wrap_Coder_Encode;

void
·_swig_wrap_Coder_Encode(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_Encode, &p);
}



#pragma dynimport _wrap_Coder_Decode _wrap_Coder_Decode ""
extern void (*_wrap_Coder_Decode)(void*);
static void (*x_wrap_Coder_Decode)(void*) = _wrap_Coder_Decode;

void
·_swig_wrap_Coder_Decode(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_Decode, &p);
}



#pragma dynimport _wrap_Coder_MaxLength _wrap_Coder_MaxLength ""
extern void (*_wrap_Coder_MaxLength)(void*);
static void (*x_wrap_Coder_MaxLength)(void*) = _wrap_Coder_MaxLength;

void
·_swig_wrap_Coder_MaxLength(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_MaxLength, &p);
}



#pragma dynimport _wrap_Coder_GetSize _wrap_Coder_GetSize ""
extern void (*_wrap_Coder_GetSize)(void*);
static void (*x_wrap_Coder_GetSize)(void*) = _wrap_Coder_GetSize;

void
·_swig_wrap_Coder_GetSize(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_GetSize, &p);
}



#pragma dynimport _wrap_Coder_Save _wrap_Coder_Save ""
extern void (*_wrap_Coder_Save)(void*);
static void (*x_wrap_Coder_Save)(void*) = _wrap_Coder_Save;

void
·_swig_wrap_Coder_Save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_Save, &p);
}



#pragma dynimport _wrap_Coder_Load _wrap_Coder_Load ""
extern void (*_wrap_Coder_Load)(void*);
static void (*x_wrap_Coder_Load)(void*) = _wrap_Coder_Load;

void
·_swig_wrap_Coder_Load(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_Load, &p);
}



#pragma dynimport _wrap_Coder_Unuse _wrap_Coder_Unuse ""
extern void (*_wrap_Coder_Unuse)(void*);
static void (*x_wrap_Coder_Unuse)(void*) = _wrap_Coder_Unuse;

void
·_swig_wrap_Coder_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_Unuse, &p);
}



#pragma dynimport _wrap_Coder_Use _wrap_Coder_Use ""
extern void (*_wrap_Coder_Use)(void*);
static void (*x_wrap_Coder_Use)(void*) = _wrap_Coder_Use;

void
·_swig_wrap_Coder_Use(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Coder_Use, &p);
}



#pragma dynimport _wrap_new_CoderNone _wrap_new_CoderNone ""
extern void (*_wrap_new_CoderNone)(void*);
static void (*x_wrap_new_CoderNone)(void*) = _wrap_new_CoderNone;

void
·_swig_wrap_new_CoderNone(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_CoderNone, &p);
}



#pragma dynimport _wrap_delete_CoderNone _wrap_delete_CoderNone ""
extern void (*_wrap_delete_CoderNone)(void*);
static void (*x_wrap_delete_CoderNone)(void*) = _wrap_delete_CoderNone;

void
·_swig_wrap_delete_CoderNone(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_CoderNone, &p);
}



#pragma dynimport _wrap_CoderNone_Encode _wrap_CoderNone_Encode ""
extern void (*_wrap_CoderNone_Encode)(void*);
static void (*x_wrap_CoderNone_Encode)(void*) = _wrap_CoderNone_Encode;

void
·_swig_wrap_CoderNone_Encode(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_Encode, &p);
}



#pragma dynimport _wrap_CoderNone_Decode _wrap_CoderNone_Decode ""
extern void (*_wrap_CoderNone_Decode)(void*);
static void (*x_wrap_CoderNone_Decode)(void*) = _wrap_CoderNone_Decode;

void
·_swig_wrap_CoderNone_Decode(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_Decode, &p);
}



#pragma dynimport _wrap_CoderNone_MaxLength _wrap_CoderNone_MaxLength ""
extern void (*_wrap_CoderNone_MaxLength)(void*);
static void (*x_wrap_CoderNone_MaxLength)(void*) = _wrap_CoderNone_MaxLength;

void
·_swig_wrap_CoderNone_MaxLength(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_MaxLength, &p);
}



#pragma dynimport _wrap_CoderNone_GetSize _wrap_CoderNone_GetSize ""
extern void (*_wrap_CoderNone_GetSize)(void*);
static void (*x_wrap_CoderNone_GetSize)(void*) = _wrap_CoderNone_GetSize;

void
·_swig_wrap_CoderNone_GetSize(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_GetSize, &p);
}



#pragma dynimport _wrap_CoderNone_Save _wrap_CoderNone_Save ""
extern void (*_wrap_CoderNone_Save)(void*);
static void (*x_wrap_CoderNone_Save)(void*) = _wrap_CoderNone_Save;

void
·_swig_wrap_CoderNone_Save(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_Save, &p);
}



#pragma dynimport _wrap_CoderNone_Load _wrap_CoderNone_Load ""
extern void (*_wrap_CoderNone_Load)(void*);
static void (*x_wrap_CoderNone_Load)(void*) = _wrap_CoderNone_Load;

void
·_swig_wrap_CoderNone_Load(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_Load, &p);
}



#pragma dynimport _wrap_CoderNone_Unuse _wrap_CoderNone_Unuse ""
extern void (*_wrap_CoderNone_Unuse)(void*);
static void (*x_wrap_CoderNone_Unuse)(void*) = _wrap_CoderNone_Unuse;

void
·_swig_wrap_CoderNone_Unuse(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_Unuse, &p);
}



#pragma dynimport _wrap_CoderNone_Use _wrap_CoderNone_Use ""
extern void (*_wrap_CoderNone_Use)(void*);
static void (*x_wrap_CoderNone_Use)(void*) = _wrap_CoderNone_Use;

void
·_swig_wrap_CoderNone_Use(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_CoderNone_Use, &p);
}



